# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1.0
workflows:
  node-tests:
    jobs:
      - node/test:
          app-dir: "~/project/sample-app"
      - build:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm test


