version: '3.8'

services:
  postgres: 
    image: postgres
    container_name: digitalbdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=digitalbdb
      - POSTGRES_PASSWORD=digitalbdb
      - POSTGRES_DB=digitalbdb
  
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "digitalbdb@digitalbdb.com"
      PGADMIN_DEFAULT_PASSWORD: "digitalbdb"
    ports:
      - "80:80"
    depends_on: 
      - postgres